script:
  - "make test"

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

branches:
  only:
    - master
    - dev
    - /^greenkeeper/.*$/

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: COVERAGE=true
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"

sudo: false
